require: 
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec


AllCops:
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  Exclude:
    - "web/node_modules/**/*"
    - "Vagrantfile"
    # - "update_repo.gemspec"
    - "bin/**/*"

Style/SymbolArray:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
    - update_repo.gemspec
